#!/usr/bin/env python

import getopt, sys

__author__ = "Adam Karl"

def main():
  numFrames = None
  pageSize = None
  alg = None
  file = None

  try:
    opts, args = getopt.getopt(sys.argv[1:], "n:p:a:")
  except:
    print("bad arguments")

  for opt, arg in opts:
    if opt in ['-n']:
      numFrames = int(arg)
    elif opt in ['-p']:
      pageSize = int(arg)
    elif opt in ['-a']:
      alg = arg
  file = args[0]


if __name__ == "__main__":
  main()
